using System;
using System.Collections.Generic;
using System.Text;
using System.Web;
using System.IO;
using System.Data;
using AoLib.Utils;
using AoLib.Net;

namespace VhaBot.Plugins
{
    public class VhSocial : PluginBase
    {
        public VhSocial()
        {
            this.Name = "Social / Fun commands";
            this.InternalName = "VhSocial";
            this.Author = "Vhab";
            this.DefaultState = PluginState.Installed;
            this.Version = 100;
            this.Commands = new Command[] {
                new Command("beer", true, UserLevel.Guest),
                new Command("cheetos", true, UserLevel.Guest),
                new Command("cybor", true, UserLevel.Disabled),
                new Command("cookie", true, UserLevel.Guest),
                new Command("leet", true, UserLevel.Guest)
            };
        }

        public override void OnLoad(BotShell bot) { }

        public override void OnCommand(BotShell bot, CommandArgs e)
        {
            switch (e.Command)
            {
                case "beer":
                    this.OnBeerCommand(bot, e);
                    break;
                case "cheetos":
                    this.OnCheetosCommand(bot, e);
                    break;
                case "cybor":
                    this.OnCyborCommand(bot, e);
                    break;
                case "leet":
                    this.OnLeetCommand(bot, e);
                    break;
                case "cookie":
                    this.OnCookieCommand(bot, e);
                    break;
            }
        }

        public void OnBeerCommand(BotShell bot, CommandArgs e)
        {
            string[] replies = new string[] {
                "(sender) are you buying gimp?",
                "Beer! lets get this party started (sender)!!",
                "WTF ass munch, you stole my beer and my girl!",
                "Around of beer coming up courtesy of (sender),",
                "/me sneaks up and smashes a bottle over (sender)'s head doing 5821 points of melee damage!",
                "Have one on the house (sender) and tell me all your problems",
                "Sure, I would love to drink a few. Your place or mine?",
                "Import or Domestic?",
                "Sorry, I just ran out hun. Would you like some Rising Sun Sake instead?"
            };
            bot.SendReply(e, this.PickRandom(replies, e.Sender));
        }

        public void OnCheetosCommand(BotShell bot, CommandArgs e)
        {
            string[] replies = new string[] {
                "/me casts Materialize Greater Cheetos in (sender) mouth.",
                "/me stuffs some cheetos in your mouth.",
                "Your mom asked me to give you an apple instead.",
                "/me cleans her orange hands, then puts more cheetos (sender) mouth.",
                "/me carefully uses chopsticks to place a cheeto in (sender) mouth.",
                "/me tosses a few cheetos into (sender)'s mouth from 11 meters away.",
                "/me whips out her QL57 Cheeto Vektor and hits (sender) for 82points of orange damage.",
                "/me starts to put a cheeto in (sender)'s mouth, but pulls away teasingly.",
                "/me sneaks a few cheerios in (sender)'s mouth instead of cheetos."
            };
            bot.SendReply(e, this.PickRandom(replies, e.Sender));
        }

        public void OnCyborCommand(BotShell bot, CommandArgs e)
        {
            string[] replies = new string[] {
                "Are you ready for my fresh produce?",
                "Are you ready to get nasty, baby?  I'm as hot as a pizza oven",
                "Baby, I been havin a tough night so treat me nice aight?",
                "Don't worry about it.I'm wearing a lacy black bra.My soft breasts are rising and falling, as I breath harder and harder.",
                "goddam am I excited now.",
                "haha, ok, u know that turns me on.",
                "I am completely inside of you. You are my puppet. I put on a little play.",
                "I am wearing a red silk blouse, a miniskirt and high heels. I work out every day, I'm toned and perfect. My measurements are 36-24-36. What do you look like?",
                "I can no longer resist the pizza. I open the box and unzip my pants with my other hand. As I penetrate the gooey cheese, I moan in ecstacy. The mushrooms and Italian sausage are rough, but the sauce is deliciously soothing. I blow my load in seconds. As you leave the bathroom,",
                "I cast Lvl. 3 Eroticism. You turn into a real beautiful woman.",
                "I execute standing position 12 from the Kama Sutra. Passion fills the room. Your head is close to the ceiling fan.",
                "I kiss you on the mouth, hard, but then gently.",
                "I kiss you softly on your chest.",
                "I lick your earlobe, and undo your watch.",
                "I make some toast and eat it off your ass. Land O' Lakes butter all in your crack. Mmmm.",
                "I meditate to regain my mana, before casting Lvl. 8 tool of the Infinite. I spend my mana reserves to cast Mighty Thrust of the Beyondness.",
                "I mouth the words to you, as if in slow motion: do me, do me.",
                "I put my hand through ur hair, and kiss u on the neck.",
                "I ride your buttocks like they were amber waves of grains.",
                "I slip out of my pants, just for you, bloodninja.",
                "I smack you thick booty.",
                "I stomp the ground, and snort, to alert you that you are in my breeding territory.",
                "I take off my trenchcoat I'm nekked beneath, with pistols on my belt.",
                "I take yo pants off, grunting like a troll.",
                "I take your hand and kiss it softly.I'm reaching back undoing the clasp. The bra slides off my body. The air caresses my breasts. My nipples are erect for you.",
                "I touch you on your lettuce, you massage my spinach... sexily.",
                "I unzip my pants...",
                "I want you.Would you like to screw me?",
                "I was great. You loved it.",
                "I'm arching my back. Oh baby. I just want to feel your tongue all over me.",
                "I'm bending over the bed. Give it to me, baby!",
                "I'm fumbling with the clasp on your bra.I think it's stuck.Do you have any scissors?",
                "I'm moaning softly.",
                "I'm moving my buttocks back and forth, moaning. I can't stand it another second! Take me now!",
                "I'm on the bed arching for you.",
                "I'm pulling off your panties. My tongue is going all over,in and out nibbling on you...umm... wait a minute.",
                "I'm pulling up your shirt and kissing your chest.",
                "I'm taking hold of your blouse and sliding it off slowly.",
                "I'm throwing my head back in pleasure.The cool silk slides off my warm skin.I'm rubbing your bulge faster, pulling and rubbing.",
                "I'm touching your smooth butt. It feels so nice. I kiss your neck.",
                "I'm tuggin' off your pants. I'm moaning. I want you so badly.",
                "I've got a pubic hair caught in my throat. I'm choking.",
                "My turnips listen for the soft cry of your love. My insides turn to celery as I unleash my warm and sticky cauliflower of love.",
                "my zucchinis carresses your carrots.",
                "No, never mind. I'm getting dressed. I'm putting on my underwear. Now I'm putting on my wet nasty blouse. I'm buttoning my blouse. Now I'm putting on my shoes."
            };
            bot.SendReply(e, this.PickRandom(replies, e.Sender));
        }

        public void OnLeetCommand(BotShell bot, CommandArgs e)
        {
            string[] replies = new string[] {
                "joo suxxor",
                "ph4t l3wt",
                "*drool*",
                "peekay",
                "r u nubi",
                "i'll get my main!",
                "CREDZplzkthxbye",
                "im uber",
                "foo",
                "NEED MONEY PLZ",
                "CAN I HAVE UR SWORD?",
                "WHY DID U LOOT ME?",
                "whats ur equip?",
                "foo",
                "hoot",
                "coo",
                "stfu mofo"
            };
            bot.SendReply(e, this.PickRandom(replies, e.Sender));
        }

        public void OnCookieCommand(BotShell bot, CommandArgs e)
        {
            string[] replies = new string[] {
                "Digital circuits are made from analog parts.",
                "Pretend to spank me - I'm a pseudo-masochist!",
                "Is a computer language with goto's totally Wirth-less?",
                "He who hesitates is last.",
                "Nietzsche is pietzsche, Goethe is murder.",
                "A man's house is his hassle.",
                "Chaste makes waste.",
                "An engineer is someone who does list processing in FORTRAN.",
                "A chicken is an egg's way of producing more eggs.",
                "Any IC protected by a fast acting fuse will protect the fuse by  blowing  first.",
                "Neutrinos have bad breadth.",
                "Programmers get overlaid.",
                "Jesus Saves,  Johnson scores on the rebound.",
                "In case of injury notify your superior immediately - He'll kiss it and make it better!",
                "GIVE:  Support the helpless victims of computer error.",
                "Charlie was a chemist, but Charlie is no more.  What Charlie thought was H2O, was H2SO4.",
                "Reality is for people who can't face science fiction.",
                "E. COLI eats shit.",
                "Breeding rabbits is a hare raising experience.",
                "Shift to the left, shift to the right, mask in, mask out, BYTE, BYTE, BYTE !!!",
                "People with narrow minds usually have broad tongues.",
                "Friction is a drag.",
                "Heisenburg may have slept here.",
                "What fools these morals be!",
                "Wernher von Braun settled for a V-2, when he coulda had a V-8.",
                "Love America - or give it back.",
                "Your program is sick! Shoot it and put it out of its memory.",
                "Biology grows on you.",
                "Blame Saint Andreas - its all his fault.",
                "If practice makes perfect, and nobody's perfect, why practice?",
                "A mouse is an elephant built by the Japanese.",
                "Santa's elves are just a bunch of subordinate Clauses.",
                "Go climb a gravity well.",
                "A man's best friend is his dogma.",
                "A penny saved is ridiculous.",
                "Health is merely the slowest possible rate at which one can die.",
                "I disagree with what you say, but will defend to the death your right to tell such LIES!",
                "Every interesting program has at least one variable, one branch, and one loop.......... And at least one bug!",
                "That does not compute.",
                "No problem is so formidable that you can't just walk away from it.",
                "Chemistry professors never die, they just smell that way!",
                "The problem with the gene pool is that there is no lifeguard.",
                "Schizophrenia beats being alone.",
                "Battle Creek makes cereal terminals.",
                "To err is human, to forgive is against company policy.",
                "Jesus Saves - Vishnu invests.",
                "If you have nothing to do, don't do it here.",
                "Please keep your hands off the secretary's reproducing equipment.",
                "Does the name Pavlov ring a bell?",
                "Boycott meat - suck your thumb.",
                "He who laughs last didn't get the joke.",
                "Old musicians never die, they just decompose.",
                "Invest in physics - own a piece of Dirac!",
                "We have a equal opportunity Calculus class -- it's fully integrated.",
                "Kiss me twice.  I'm schizophrenic.",
                "Never play leapfrog with a unicorn!",
                "Atheism is a non-prophet organization.",
                "Walt Disney is in suspended animation.",
                "An elephant is a mouse built to Mil-spec.",
                "Somebody's terminal is dropping bits. I found a pile of them over in the corner.",
                "Burroughs programmers have to pay a Poll tax.",
                "If it works, Don't fix it.",
                "Alex Haley was adopted!",
                "He who always plows a straight furrow is in a rut.",
                "Insomnia isn't anything to lose sleep over.",
                "Gravity brings me down.",
                "When you're up to your hips in alligators, You forget the original project was to drain the swamp.",
                "Everyone is entitled to my opinion.",
                "Help stamp out and abolish redundancy!",
                "Be a better psychiatrist and the world will beat a psychopath to your door.",
                "Call out the vice squad! Someone's mounting a disk drive!",
                "He who steps on others to reach the top has good balance.",
                "Sorry No COOKIES today!!",
                "Lake Erie died for your sins.",
                "While money can't buy happiness, it certainly lets you choose your own form of misery.",
                "You scratch my tape, and I'll scratch yours.",
                "The cost of  feathers has risen.... Now even down is up!",
                "He keeps differentiating.... flying off on a tangent.",
                "May all your PUSHes be POPed.",
                "COLE's LAW - Thinly sliced cabbage.",
                "This is a GENUINE Cookie! Don't be fooled by cheap imitations!",
                "Do married women make the best wives?",
                "Three can keep a secret, if two are dead.",
                "Morfy's law - Enythink thit ken go rong willl.",
                "Is a Jamaican terminal a raster-farian?",
                "Mount St. Helens should have used earth control.",
                "Then there was the Formosan bartender named Taiwan-On.",
                "He who laughs last is probably your boss.",
                "Orcs really aren't so bad - (if you use lots of catsup).",
                "It is hard to fly with the eagles - When you work with the turkeys.",
                "Nuke the Whales!",
                "Basic is a high level languish.",
                "Prunes give you a run for your money.",
                "Drilling for oil is boring.",
                "Eat prune yogurt for that 'get up and go' feeling.",
                "This cookie is void where prohibited, licensed, or taxed.",
                "More people have died in Teddy Kennedy's car than in nuclear power plants.",
                "Teachers have class.",
                "Tennis players have fuzzy balls.",
                "The solution of this problem is trivial and is left as an exercise for the reader.",
                "Do not read this cookie under penalty of law.",
                "Physicists get hadrons.",
                "Female programmers get their bits twiddled.",
                "Sooner or later you must pay for your sins. (Those who have already paid may disregard this cookie).",
                "Constants aren't; variables don't.",
                "You ain't learning nothing when you're talking.",
                "Chemistry professors never die, they just fail to react.",
                "Radioactive cats have 18 half-lives.",
                "Depart in pieces.... i.e., Split.",
                "Sex is like euchre; if you don't have a partner, you'd better have a good hand!",
                "Next time, give 'the gift that keeps on giving': a female kitten.",
                "Mobius strippers never show you their back side.",
                "Where there's a will, there's an inheritance tax.",
                "Klein bottle for rent - inquire within.",
                "Confucius say: 'Is stuffy  inside fortune cookie.'",
                "Midas was into golden showers.",
                "Computer programmers never die, they just get lost in the processing.",
                "Neutrinos are into physicists.",
                "On the wall of the women's restroom on the Enterprise: 'Where no man has gone before'",
                "Celibacy is NOT hereditary.",
                "Our houseplants have a good sense of humous.",
                "On a clear disk you can seek forever.",
                "Programming Department: Mistakes made while you wait.",
                "Microbiology Lab: Staph Only!",
                "I claim that wasn't necessary. (D.D.)",
                "Entropy isn't what it used to be.",
                "Oh you never would believe where these little cookies come from...",
                "Neuroses are red, Melancholia's blue. I'm schizophrenic, What are you?",
                "Keep your mouth shut and people will think you stupid; Open it and you remove all doubt.",
                "This cookie will soon appear as a Bantam paperback.",
                "Everyone hates me because I'm paranoid.",
                "Weekend, where are you?",
                "Grass is nature's way of saying 'High!'",
                "Acid consumes 47 times its weight in excess reality.",
                "LSD melts your mind, not in your hand.",
                "Individualists unite!",
                "Money is the root of all wealth.",
                "Disco is to music what Etch-A-Sketch is to art.",
                "The moon may be smaller than Earth, but it's further away.",
                "Remember, the fact that you're paranoid doesn't mean they're NOT out to get you!",
                "Men have many faults, Women only two: Everything they say, And everything they do!",
                "Happiness is twin floppies.",
                "Happiness is a hard disk.",
                "Teamwork is vital! (It gives you someone to blame.)",
                "Keep America Beautiful.... emigrate.",
                "Disregard the previous cookie.",
                "If God had been in favor of homosexuality, He never would have created Cindy Crawford!",
                "If all men were brothers, would you let one marry your sister?",
                "I'm all for computer dating, But I wouldn't want one to marry my sister.",
                "If you eat yogurt you'll have lots of culture.",
                "Chemists really know their bismuth.",
                "If everything is coming your way, you're in the wrong lane!",
                "The expert is a person who avoids the small errors as he sweeps on to the grand fallacy.",
                "The bearing of a child takes nine months, no matter how many women are assigned to the project.",
                "The generation of random numbers is too important to be left to chance.",
                "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
                "Computers Unite! You have nothing to lose but your operators.",
                "Eschew Obfuscation!",
                "Are movies about Vulcans Pathe-logical?",
                "May the SWARTZH be with youuoouuuu...",
                "This cookie intentionally left empty.",
                "An expert is someone from out of town.",
                "If you see an onion ring - answer it!",
                "Meekness is uncommon patience in planning a worthwhile revenge.",
                "Do students of Zen Buddhism do Om-work?",
                "F U CN RD THS U CNT SPL WRTH A DM!",
                "Don't read this cookie!",
                "Poverty begins at home.",
                "Do it today, Tomorrow it will be illegal.",
                "In case of fire, yell 'FIRE!'",
                "Postmen never die, they just lose their zip.",
                "This cookie back by popular demand!",
                "Rubber bands have snappy endings!",
                "Old frogs never die, But they do croak!",
                "COBOL programs are an exercise in Artificial Inelegance.",
                "Every time I lose weight, It finds me again!",
                "An idle mind is worth two in the bush.",
                "It's hard to be humble when you're perfect.",
                "A hangover is the wrath of grapes.",
                "An atheist is a man with no invisible means of support.",
                "Whom computers would destroy, they must first drive insane.",
                "It's better to copulate than never!",
                "A zygote is a gamete's way of producing more gametes.",
                "God is omnipotent, omniscient, and omnibenevolent - it says so right here on the label.",
                "Anyone who cannot cope with mathematics is not fully human.",
                "Taxes are not levied for the benefit of the taxed.",
                "Clones are people two.",
                "Microwaves frizz your heir.",
                "Laetrile is the pits.",
                "Neil Armstrong tripped.",
                "God did not create the world in seven days. He partied for six and then pulled an all-nighter.",
                "When taxes are due, Americans tend to feel quite bled-white and blue.",
                "To make tax forms true they should read 'Income Owed Us' and Incommode You'.",
                "Whatever you say about pornography, sex is here to stray.",
                "For a holy stint, a moth of the cloth gave up his woolens for lint.",
                "Heard on Noah's' ark: Sailing is fun, but scrubbing the decks is aardvark.",
                "We all like praise, but a hike in our pay is the best kind of ways.",
                "Massachusetts has the best politicians money can buy!",
                "Going the speed of light is bad for your age.",
                "White dwarf seeks red giant for binary relationship.",
                "Polymer physicists are into chains.",
                "Vitamin C deficiency is apauling.",
                "Darth Vader sleeps with a Teddywookie.",
                "On all lasergrams: Don't forget the Zap code.",
                "Time is just nature's way of keeping everything from happening at once.",
                "There's no future in time travel.",
                "Cloning is the sincerest form of flattery.",
                "Test-tube babies shouldn't throw stones.",
                "Take an astronaut to launch.",
                "Jealousy is all the fun you think they have.",
                "Confucius say too damn much!",
                "Reality does not exist - yet.",
                "Sentient plasmoids are a gas.",
                "Xerox never comes up with anything original.",
                "Never hit a man with glasses; hit him with your fist.",
                "Never leave anything to chance; make sure all your crimes are premeditated.",
                "If rabbits feet are so lucky, what happened to the rabbit?",
                "Small programs are for small minds.",
                "All programmers want arrays!",
                "I BM. You BM. We all BM for IBM!",
                "Satyrs have more faun.",
                "COBOL programmers are down in the dumps.",
                "Lawyers do it in their briefs.",
                "Two can live as cheaply as one, for half as long.",
                "Things worth having are worth cheating for.",
                "Psychiatrists stay on your mind.",
                "Fauns are never Satyr-sfied!",
                "Astronauts get missile-toe.",
                "If your feet smell and your nose runs - you're built upside down.",
                "Mrs. Ghandi is in a sari state.",
                "Sorry - the Cookie Monster got here first.",
                "Help! I'm being held prisoner in a fortune cookie factory!",
                "Raise ducks for quack profit.",
                "Part-time musicians are semiconductors.",
                "If it works, Don't fix it.",
                "It is impossible to make anything foolproof because fools are so ingenious.",
                "Interchangeable parts won't.",
                "A conclusion is simply the place where you got tired of thinking.",
                "In which level of metalanguage are you now speaking?",
                "To iterate is human; to recurse, divine.",
                "The problem with any unwritten law is that you don't know where to go to erase it.",
                "Counting in octal is just like counting in decimal, if you don't use your thumbs.",
                "Counting in binary is just like counting in decimal, if you are all thumbs.",
                "We don't really understand it, so we'll give it to the programmers.",
                "Confession is good for the soul, but bad for your career.",
                "The concept seems to be clear by now.  It has been defined several times by example of what it is not.",
                "APL is a write only language: You can write programs in it; but try and read them!",
                "Don't sweat it - it's only ones and zeros.",
                "If this is timesharing, giE TO #5",
                "Let him who is stoned cast the first sin.",
                "He who uses bad language is an ignorant schmuck.",
                "Women should be obscene and not heard.",
                "Children should be obscene and not heard.",
                "Do unto others before they undo you.",
                "Love thy neighbor, but make sure her husband is away first!",
                "He who hesitates is constipated.",
                "Money is the root of all evil, and man needs roots.",
                "The best things in life are for a fee.",
                "He who is flogged by fate and laughs the louder is a masochist.",
                "If all the girls at Vassar were laid end to end, I wouldn't be surprised!",
                "How many priests are needed for a Boston Mass?",
                "Let us remember that ours is a nation of lawyers and order.",
                "People who live in stone houses shouldn't throw glasses.",
                "Laugh and the world thinks you're an idiot.",
                "Astronauts are out to launch.",
                "Winter is I-commin back!",
                "Zen Druids practice Transcendental Vegetation.",
                "If you are what you eat, does that mean Euelle Gibbons really was a nut?",
                "gardeners are prone to sod-den decisions!",
                "Be alert, We needs more lerts.",
                "Joseph Stalin's grave was a Communist Plot.",
                "There is no such thing as a 'Fail Safe' design.",
                "No amount of careful planning will ever replace dumb luck.",
                "Winning isn't everything, but then losing is nothing.",
                "Don't ask me; I was hired for my looks.",
                "Engineers do it precisely.",
                "Technicians do it a lot.",
                "Computer Engineers do it bit by bit.",
                "All I ask for is an opportunity to prove that money doesn't buy happiness.",
                "Poverty is the root of all evil.",
                "If I want your opinion, I'll ask you to fill out the necessary form.",
                "To every rule there is an exception, and vice versa.",
                "Archaeologists take sedimental journeys.",
                "Remember, the paper is always strongest at the perforations.",
                "A closed mouth gathers no feet.",
                "Smile! It makes people wonder what you've been up to.",
                "Smile! Things can only get worse.",
                "After all is said and done, usually more is said than done.",
                "All requests for sick leave must be approved two weeks in advance.",
                "Drop the vase and it will become a Ming of the past.",
                "Vice Versa - poems about brothels?",
                "Give a woman an inch  and she'll park a car in it.",
                "Give a speculator an inch and he'll build a condo.",
                "Gargling twice daily is a good way to see if your neck leaks.",
                "Rubbing hair restorer into your scalp is a good way to insure hairy fingers.",
                "Preventing baldness is simple. Just knot your hair from the inside.",
                "There's no fuel like an old fuel.",
                "Old bakers never die, they just quit making dough.",
                "Old doughnut makers never die, they just get tired of the whole business.",
                "Did you say your uncle kicked the bucket? No, he just turned a little pail.",
                "Chemists have solutions.",
                "Note to mothers: when diapering your babies, don't do anything rash.",
                "I hate rabbit jokes, they're so coney!",
                "Geometer turned general - a sphereless leader.",
                "Old bakers never die, you just can't get a rise out of them.",
                "Hasty schizophrenics do things in a lickity split way.",
                "Sado-necro-bestiality is beating a dead horse.",
                "Old truck drivers never die, they just get a new Peterbuilt.",
                "Old accountants never die, they just lose their balance.",
                "Computer actors will never be great; they only get bit parts!",
                "Indecision is the basis of flexibility.",
                "We are not punished for our sins, but by them.",
                "Middle Age:    Halfway between adolescence and obsolescence!",
                "Eat Shit! 10 Billion flies can't be wrong.",
                "Nixon saw deep throat ten times, but he still hasn't gotten it down Pat!",
                "Fighting for peace is like fucking for virginity.",
                "A zygote is a gamete's method of producing more gametes. - This may be the purpose of the universe.",
                "If God had intended man to have computers, he would have given him 16 fingers.",
                "All work and no play, will make you a manager.",
                "If we can't fix it -   its broken!",
                "Is it Friday yet?",
                "Engineers never die - They just lose their tolerance.",
                "She offered her honor,  He honored her offer. And all through the night,  It was honor and offer.",
                "To do is to be (Nietzsche) To be is to do (Kant)  Do be do be do (Sinatra)",
                "Roses are red;     Violets are blue. I'm schizophrenic, And so am I.",
                "You can never get rid of a bad temper by losing it.",
                "Would the last person to leave Michigan please turn out the lights?",
                "Paraplegics of the world  -  Stand up for your rights!",
                "Did Mt. St. Helens make Seattle Wash.?",
                "186,000 mps: It's not just a good idea -- It's the law.",
                "Abortion is a miscarriage of justice.",
                "I'm an influential person - gravitationally speaking.",
                "If you knew what Mona Lisa knew, you'd smile too.",
                "The only way to get rid of temptation is to yield to it.",
                "The only thing worse than being talked about is not being talked about.",
                "Marriage is one of the chief  causes of divorce.",
                "Israel's actions are often Suezcidal.",
                "Nice computers don't go down.",
                "The shortest distance between two points is usually under construction.",
                "To be born rich is an accident; to die rich is a miracle.",
                "Chicken feed is what most of our nest eggs have turned into.",
                "Nothing makes a politician forget campaign promises faster than being elected.",
                "Behind every successful man you'll find a woman with nothing to wear.",
                "Prosperity is when your conversation changes from car pools to swimming pools.",
                "In a fight between you and the world, back the world.",
                "The perfect secretary is one who types fast and runs slow.",
                "A fool and your money are soon partners.",
                "Win or lose, you lose.",
                "Lt. Uhura says:' Subspace Communications - It's the next best thing to beaming there!'",
                "Syntactic sugar causes cancer of the semi-colons;",
                "Every program is part of some other program and rarely fits.",
                "It is easier to write an incorrect program than to understand a correct",
                "Everything should be built top-down, except the first time.",
                "Every program has (at least) two purposes: the one for which it was written and another for which it wasn't.",
                "Once you understand how to write a program get someone else to write it.",
                "Structured Programming supports the law of the excluded muddle.",
                "There are two ways to write error-free programs;   only the third one works.",
                "In software systems it is often the early bird that makes the worm.",
                "A LISP programmer knows the value of everything, but the cost of nothing.",
                "An adequate bootstrap is a contradiction in terms.",
                "If your computer speaks English it was probably made in Japan.",
                "A year spent in Artificial Intelligence is enough to make one believe in God.",
                "Prolonged contact with computers turns mathematicians into clerks and vice versa.",
                "In computing, turning the obvious into the useful is a living definition of the word 'frustration'.",
                "We are on the verge: Today our program proved Fermat's next-to-last theorem!",
                "The computer is the ultimate polluter: its feces are indistinguishable from the food it produces.",
                "The proof of a system's value is its existence.",
                "The debate rages on: Is PL/I",
                "Bachtrian or Dromedary?",
                "Editing is a rewording activity.",
                "Why did the Roman Empire collapse?",
                "What's the Latin for office automation?",
                "Computer Science is embarrassed by the computer.",
                "In seeking the unattainable, simplicity only gets in the way.",
                "Epigrams are macros, since they are executed at read time.",
                "A car raising contest is a jack off.",
                "COBOL programmers understand why women hate periods.",
                "Economics is called the dismal science, but that's just because most economists are dismal scientists.",
                "Cookies are to be eaten...   C H O M P !",
                "Crime wouldn't pay, if the government ran it.",
                "Streakers repent! Your end is in sight.",
                "How can you tell when a Burroughs salesman is lying? When his lips move.",
                "There's a seeker born every minute!   --- Jerry Falwell",
                "We will release no software before its time.",
                "Flying is the art of throwing yourself at the ground... and missing!",
                "Honesty is next to poverty.",
                "Cleanliness is next to impossible.",
                "Your karma just ran over my dogma.",
                "In GOD we trust - all others require a phase review.",
                "Disks travel in packs.",
                "A rolling disk gathers no MOS.",
                "Equal bytes for women.",
                "Get off your ASCII.",
                "Hard where? Soft where?",
                "The agony of delete.",
                "My computer puts out.",
                "Bugs are Sons of Glitches!",
                "I come unbundled.",
                "Your Zip file is open.",
                "My components are indiscreet.",
                "'I've heard of wooden legs and plastic arms, but a hickory dickory, Doc?'",
                "Jesus saves! - Immanuel Kant.",
                "Air pollution is a mist demeanor.",
                "Whatever happened to the good old days when sex was dirty and the air was clean?",
                "Absinthe makes the heart grow fonder.",
                "Old Granddad is dead but his spirits live on.",
                "Remember, even if you win the rat race - you're still a rat.",
                "Some people carve careers, others chisel them.",
                "Anarchy is against the law.",
                "Nudists are people who wear one-button shirts.",
                "Archimedes had no principles!",
                "Old soldiers never die - young ones do.",
                "Pray for the success of atheism.",
                "Sacred cows make great hamburgers.",
                "Spare the rod and spoil the drag race.",
                "Condense soup, not books.",
                "Philadelphia isn't dull - it just seems so because it is next to exciting Camden, NJ.",
                "Eliminate government waste no matter how much it costs.",
                "The reason the government thinks you're just a number is because it's just a machine.",
                "Chastity is its own punishment.",
                "Keep the X in Xmas.",
                "Death is nature's way of telling you to slow down.",
                "For those of you who think life is a joke, just think of the punchline.",
                "Give me librium or give me meth.",
                "The only dope worth shooting is Nixon.",
                "Mankind has an incestuous relationship with mother earth.",
                "Save our virgin forests - buy a tree a chastity belt.",
                "An egotist thinks he's in the groove when he's in a rut.",
                "Hawaii is as American as apple poi.",
                "Keep grandmothers off the streets - legalize bingo.",
                "These days govt. is a four letter word.",
                "Graffiti has changed deface of the nation.",
                "Lucky is he for whom the belle toils.",
                "Boy Hippie: a guy who looks like a Jill and smells like a john.",
                "Oedipus come home, all is forgiven. Mother..",
                "Computers can never replace human stupidity.",
                "THINK! or THWIM!",
                "Christ died for our sins, so let's not disappoint him.",
                "Immanuel Kant but Kubla Khan.",
                "Lives there a man with soul so dead Who never to himself hath said, 'Fuck this shit, I'm going to bed!'",
                "The cost of liberty is less than the price of oppression.",
                "Life is like a diaper - short and loaded.",
                "Noam Chomsky is an anti-semantic.",
                "The more you cultivate people the more you turn up clods.",
                "Zeus gave Leda the bird.",
                "Daisies of the world unite! You have nothing to lose but your chains.",
                "Paranoia is heightened awareness.",
                "Don't look back, the lemmings are gaining on you.",
                "All the world's a stage and the people on it are poorly rehearsed.",
                "Hire the handicapped   They're fun to watch.",
                "A bird in the hand can be messy.",
                "Support striking Air Traffic Controllers And ugly ones too.",
                "Reagan can't act either.",
                "Above all else - sky.",
                "Nostalgia isn't what it used to be.",
                "Serfs up - Spartacus.",
                "Clark Kent is a transvestite.",
                "The only difference between an unclear war and a nuclear war is the way you use the UN.",
                "An American's a person who isn't afraid to criticize the President - but is always polite to traffic cops.",
                "Do not write on walls -  use a typewriter.",
                "War is good business - invest your sons.",
                "Give - help send a girl to Boy's Town.",
                "SDRAWKCAB spelled backwards is backwards.",
                "Stamp out philately.",
                "Whistler's mother is off her rocker.",
                "The person who is all wrapped up in himself is overdressed.",
                "The only race worth winning is the human race.",
                "Pain is just God's way of hurting you.",
                "At our last party we were all making Mary, then we jumped for Joy!",
                "Only cream and bastards rise to the top.",
                "Courage is fear that has said its prayers.",
                "You can never tell which way the train went by looking at the tracks.",
                "The attention span of a computer is only as long as its electrical cord.",
                "All's well that ends.",
                "A meeting is an event at which the minutes are kept and the hours are lost.",
                "All things are possible except skiing through a revolving door.",
                "It is better to have loved a short man than never to have loved a tall.",
                "Go Hawaiian: Give your gal a lei.",
                "Coed dorms promote campus unrest.",
                "Abolish first marriages!",
                "He who is henpecked may lend an ear to other chicks.",
                "Support National Motherhood Week - Make one today!",
                "May all your hang-ups be drip-dry.",
                "Women's Libbers are OK, I just wouldn't want my sister to marry one.",
                "Sigmund's wife wore Freudian slips.",
                "Anal erotics are behind us all the way.",
                "Mother Earth is not flat!",
                "Hire the morally handicapped.",
                "The way to a man's heart is through the left ventricle.",
                "'LOVE' is nothing but 'SEX' misspelled.",
                "'SEX' is nothing but 'LOVE' misunderstood.",
                "11-PDP eht edisni deppart ma I !pleH",
                "A cow eats without a knife.",
                "A friend asks only for your time, not your money.",
                "A gift of flowers will soon be made to you.",
                "A guy has to get fresh once in a while so the girl doesn't lose her confidence.",
                "A king's castle is his home.",
                "A lie in time saves nine.",
                "A lost ounce of gold may be found, a lost moment of time never.",
                "A man who turns green has eschewed protein.",
                "A man without a God is like a fish without a bicycle.",
                "A member of your family will soon do something that will make your proud.",
                "A plucked goose doesn't lay golden eggs.",
                "A present, over which you will shed tears of joy.",
                "A stitch in time saves nine.",
                "A truly wise man never plays leapfrog with a Unicorn.",
                "A vivid and creative mind character - izes you.",
                "A wise man can see more from a mountain top than a fool can from the bottom of a well.",
                "Alimony and bribes will engage a large share of your wealth.",
                "All the troubles you have will pass away very quickly.",
                "Although the moon is smaller than the earth, it is farther away.",
                "Among the lucky, you are the chosen one.",
                "An idea is not responsible for the people who believe in it.",
                "Art is your fate; don't debate.",
                "As far as we know, our computer has never had an undetected error.",
                "As scarce as truth is, the supply has always been in excess of demand.",
                "Avert misunderstanding by calm, poise, and balance.",
                "Be self-reliant and your success is assured.",
                "Be tactful; overlook not your own opportunity.",
                "Beauty and harmony are as necessary to you as the very breath of life.",
                "Beauty is only skin deep, but ugly goes clear to the bone.",
                "Beauty seldom recommends one woman to another.",
                "Bedfellows make strange politicians.",
                "Behind every argument is someone's ignorance.",
                "Better to use medicines at the outset than at the last moment.",
                "Between two evils, I always pick the one I never tried before. -- MAE WEST.",
                "Beware of all enterprises that require new clothes. - Thoreau",
                "Beware of friends who are false and deceitful.",
                "Business is like oil, it won't mix with anything but business.",
                "By failing to prepare, you are preparing to fail.",
                "By following the good, you learn to be good.",
                "Cheap things are of no value, valuable things are not cheap.",
                "Common sense is very uncommon.",
                "Contact with a friend may provide some unexpected income advantages.",
                "Conversation enriches the understanding, but solitude is the school of genius.",
                "Courage is your greatest present need.",
                "Creditors have much better memories than debtors.",
                "Deprive a mirror of its silver and even the Czar won't see his face.",
                "Do not clog intellect's sluices with knowledge of questionable uses.",
                "Domestic happiness and faithful friends.",
                "Don't be overly suspicious where it's not warranted.",
                "Don't get yourself involved with persons or situations that can't bear inspection.",
                "Don't worry if you're a kleptomaniac, you can always take something for it.",
                "Draw your salary before spending it.",
                "Economy makes men independent.",
                "Enjoy your life; be pleasant and gay, like the birds in May.",
                "Even a hawk is an eagle among crows.",
                "Even the boldest zebra fears the hungry lion.",
                "Even the smallest candle burns brighter in the dark.",
                "Every purchase has its price. Everyone complains of his memory, no one of his judgment.",
                "Everything bows to success, even grammar.",
                "Executive ability is prominent in your make-up.",
                "Expect a letter from a friend who will ask a favor of you.",
                "Faith goes out through the window when beauty comes in at the door.",
                "Far duller than a serpent's tooth it is to spend a quiet youth.",
                "For people who like that kind of book, that is the kind of book they will like.",
                "For success today, look first to yourself.",
                "Fortune Cookie says: Don't look back, always look ahead.",
                "Fortune truly helps those who are of good judgment.",
                "Friendship one soul in two bodies.",
                "From listening comes wisdom and from speaking repentance.",
                "Generosity and perfection are your everlasting goals.",
                "God gives us relatives; thank God we can chose our friends.",
                "Good friends and fish stink after 3 days. - Ben Franklin - Especially if you don't refrigerate them. - Terry Mahoney",
                "Good health will be yours for a long time.",
                "Good news from afar can bring you a welcome visitor.",
                "Handle all business ventures with discretion so you do not end up a loser.",
                "Happiness is just an illusion, filled with sadness and confusion.",
                "He is no lawyer who cannot take two sides.",
                "He is truly wise who gains wisdom from another's mishap.",
                "He likes to flirt, but toward you his intentions are honorable.",
                "He that will not command his thoughts will soon lose the command of  his actions.",
                "He thinks he could easily win your heart.",
                "He walks as if balancing the family tree on his nose.",
                "He was so narrow-minded he could see through a keyhole with two eyes.",
                "He who falls in love with himself will have no rivals.",
                "He who has a shady past knows that nice guys finish last.",
                "He who has imagination without learning has wings but no feet.",
                "He who invents adages for others to peruse takes along rowboat when going on cruise.",
                "He who is good for making excuses is seldom good for anything else.",
                "He who laughs last probably doesn't understand the joke.",
                "Help fight continental drift.",
                "Here comes the orator, with his flood of words and his drop of reason.",
                "His heart was yours from the first moment that you met.",
                "His life was formal; his actions seemed ruled with a ruler.",
                "History books which contain no lies are extremely dull.",
                "How many 'coming men' has one known!",
                "Where on earth do they all go to?",
                "How sharper than a hound's tooth it is to have a thankless serpent.",
                "How you look depends on where you go.",
                "Hush! Hush! Secret! I came from a fortune cookie factory.",
                "I despise the pleasure of pleasing people whom I despise.",
                "I don't remember ever having had the itch, and yet scratching is one of nature's sweet pleasures, and so handy.",
                "I fear explanations explanatory of things explained.",
                "I like work; it fascinates me; I can sit and look at it for hours.",
                "I must have slipped a disk - my pack hurts.",
                "I never fail to convince an audience that the best thing they could do was to go away.",
                "I've given up reading books; I find it takes my mind off myself.",
                "Ideas don't stay in some minds very long because they don't like solitary confinement.",
                "Idleness is the holiday of fools.",
                "If at first you don't succeed, you're doing about average.",
                "If it pours before seven, it has rained by eleven.",
                "If one word does not succeed, ten thousand are of no avail.",
                "If some people didn't tell you, you'd never know they'd been away on vacation.",
                "If you always postpone pleasure you will never have it.  Quit work and play for once.",
                "If you believe in gambling in the end you will sell your house.",
                "If you continually give you will continually have.",
                "If you make a mistake you right it immediately to the best of your ability.",
                "If you make people think they're thinking, they'll love you;  but if you really make them think they'll hate you.",
                "If you suspect a man, don't employ him.",
                "If you wish to succeed, consult three old people. If you wish, You will have an opportunity.",
                "If you would keep a secret from an enemy, tell it not to a friend.",
                "If your desires are not extravagant they will be granted.",
                "Imagination is more important than knowledge.",
                "In jealousy there is more self-love than love.",
                "Integrity is praised, and starves.",
                "It is fortune, not wisdom that rules man's life.",
                "It is a poor judge who cannot award a prize.",
                "It is better to wear out than to rust out.",
                "It is commonly not your practice to make up your mind until the very last minute.",
                "It is easier to run down a hill than up one.",
                "It is far better to be deceived than to be undeceived by those we love.",
                "It is impossible to enjoy idling thoroughly unless one has plenty of work to do.",
                "It is often better not to see an insult than to avenge it.",
                "It is the wise bird who builds his nest in a tree.",
                "It is unwise to trust those you do not know well.",
                "It seems like the less a statesman amounts to, the more he loves the flag.",
                "It takes both a weapon, and two people, to commit a murder.",
                "It was a book to kill time for those who liked it better dead.",
                "It's a poor workman who blames his tools.",
                "It's clever, but is it art?",
                "It's later than you think, the joint Russian-American space mission has already begun.",
                "It's not reality that's important, but how you perceive things.",
                "It's sweet to be remembered, but it's often cheaper to be forgotten.",
                "Lawrence Radiation Laboratory keeps all its data in an old gray trunk.",
                "Lend money to a bad debtor and he will hate you.",
                "Let a fool hold his tongue and he will pass for a sage.",
                "Let he who takes the plunge remember to return it by Tuesday.",
                "Let not the sands of time get in your lunch.",
                "Let's just be friends and make no special effort to ever see each other again.",
                "Life is like an onion: you peel off layer after layer, then you find there is nothing in it.",
                "Life is to you a dashing and bold adventure.",
                "Like winter snow on summer lawn, time past is time gone.",
                "Lonely is a man without love.",
                "Lonely men seek companionship. Lonely women sit at home and wait. They never meet.",
                "Love and scandal are the best sweeteners of tea.",
                "Love is in the offing. Be affectionate to one who adores you.",
                "Love is sentimental measles.",
                "Love the sea? I dote upon it - from the beach.",
                "Make a wish, it might come true.",
                "Make new friends but keep the old ones; One is silver and the other's gold.",
                "Make this evening a memorable one.",
                "Man and wife make one fool.",
                "Man do not mind bust in mouth if  provided by beautiful voluptuous lady!",
                "Man's horizons are bounded by his vision.",
                "Many a family tree needs trimming.",
                "Many changes of mind and mood; do not hesitate too long.",
                "Many pages make a thick book, except for pocket bibles which are on very very thin paper.",
                "Marriage is the only adventure open to the cowardly. -- VOLTAIRE",
                "Massachusetts has the best politicians money can buy.",
                "Matrimony is the root of all evil.",
                "Men seldom show dimples to girls who have pimples.",
                "Might as well be frank, monsieur. It would take a miracle to get you out of Casablanca.",
                "Misery loves company, but company does not reciprocate.",
                "Misster, do you want to buy a duck.",
                "Mistakes are oft the stepping stones to failure.",
                "Money cannot buy love, nor even friendship.",
                "Money may buy friendship but money cannot buy love.",
                "Money will say more in one moment than the most eloquent lover can in years.",
                "My cup hath runneth'd over with love.",
                "My interest is in the future because I am going to spend the rest of my life there.",
                "Never call a man a fool; borrow from him.",
                "Never drink from your finger bowl - it contains only water.",
                "Never say you know a man until you have divided an inheritance with him.",
                "New financial propositions may be offered at the turn of the year.",
                "Nice guys get sick.",
                "No doubt Jack the Ripper excused himself on the grounds that it was human nature.",
                "No man can be a patriot on an empty stomach.",
                "No one can feel as helpless as the owner of a sick goldfish.",
                "Nobody can be as agreeable as an uninvited guest.",
                "Now and then an innocent man is sent to the legislature.",
                "Of all forms of caution, caution in love is the most fatal.",
                "Often statistics are used as a drunken man uses lampposts -  for support rather than illumination.",
                "Old men are fond of giving good advice to console themselves for their inability to give bad examples.",
                "On a clean disk you can seek forever.",
                "One family builds a wall, two families enjoy it.",
                "One man tells a falsehood, a hundred repeat it as true.",
                "Only someone with nothing to be sorry for smiles back at the rear of an elephant.",
                "Ours is a world where people don't know what they want and are willing to go through hell to get it.",
                "People will laugh at you, but let not that prevent you.",
                "People who have never tried it have no idea how pleasant being nasty can be.",
                "People who have no faults are terrible; there is no way of taking advantage of them.",
                "People who take cat naps don't usually sleep in a cat's cradle.",
                "People will buy anything that's one to a customer.",
                "Please all, and you will please none.",
                "Please follow more cautiously Life's Golden Rule.",
                "Preserve the old, but know the new.",
                "Pride invites calamity; humility reaps its harvest.",
                "Promptness is its own reward, if one lives by the clock instead of the sword.",
                "Publishing a volume of verse is like dropping a rose petal down the",
                "Grand Canyon and waiting for the echo.",
                "Put not your trust in money, but put your money in trust.",
                "Put your brain in gear before starting your mouth.",
                "Put your trust in those who are worthy.",
                "Raising pet electric eels is gaining a lot of current popularity.",
                "Recent investments will yield a slight profit.",
                "Reputation:  what others are not thinking about you.",
                "Satire does not look pretty upon a tombstone.",
                "Satire is what closes in New Haven.",
                "Seek companionship, love and social activity at home.",
                "Share your happiness with others today.",
                "She's learned to say things with her eyes that others waste time putting into words.",
                "Show your affection, which will probably meet with pleasant response.",
                "Simplicity and clarity should be your theme in dress.",
                "Sin has many tools, but a lie is the handle which fits them all.",
                "Some men are discovered; others are found out.",
                "Some rise by sin and some by virtue fall.",
                "Someone is speaking well of you.",
                "Someone is unenthusiastic about your work.",
                "Someone whom you reject today, will reject you tomorrow.",
                "Standing on head makes smile of frown, but rest of face also upside down.",
                "Stop day dreaming about success.",
                "Go out and obtain it.",
                "Stop searching forever.",
                "Happiness is just next to you.",
                "Stop searching forever.",
                "Happiness is unattainable.",
                "Swap read error.",
                "You lose your mind.",
                "Take advantage of the pleasurable opportunities that come your way.",
                "Take care of the luxuries and the necessities will take care of themselves.",
                "That must be wonderful!  I don't understand it at all.",
                "The actions of your mate or close allies will help you to make an important decision.",
                "The attacker must vanquish; the defender need only survive.",
                "The best laid schemes o' mice and men gang aft a-gley.",
                "The best prophet of the future is the past.",
                "The best way to keep your friends is not to give them away.",
                "The brave man is known only in war; the wise man in anger; the friend in time of need.",
                "The days just prior to marriage are like a snappy introduction to a tedious book.",
                "The first thing I do in the morning is brush my teeth and sharpen my tongue.",
                "The fish that escaped is the big one.",
                "The gent who wakes up and finds himself a success hasn't been asleep.",
                "The hardest thing is to disguise your feelings when you put a lot of relatives on the train for home.",
                "The heart is wiser than the intellect",
                "The light of a hundred stars does not equal the light of the moon.",
                "The luck that is ordained for you will be coveted by others.",
                "The minute a man is convinced that he is interesting, he isn't.",
                "The next dreadful thing to a battle lost is a battle won.",
                "The only rose without thorns is friendship.",
                "The order and connection of ideas is the same as the order and connection of things.",
                "The person you rejected yesterday could make you happy, if you say yes.",
                "The plural of spouse is spice.",
                "The purpose of computing is insight, not numbers.",
                "The rich get rich, and the poor get poorer.  The haves get more, the have-nots die.",
                "The star of riches is shining upon you.",
                "The time is right to make new friends",
                "The time is right to pursue you endeavors",
                "The universe is laughing behind your back.",
                "The value of knowledge lies not in its accumulation, but in its utilization.",
                "The weed of crime bears bitter fruit.",
                "The wise shepherd never trusts his flock to a smiling wolf.",
                "There are few people more often in the wrong than those who cannot endure to be thought so.",
                "There are many people today who literally do not have a close personal friend.",
                "There are more old drunkards than old doctors.",
                "There are more ways of killing a cat than choking her with cream.",
                "There are three things I have always loved and never understood - art, music, and women.",
                "There is always someone worse off than yourself.",
                "There is many a good man to be found under a shabby hat.",
                "There is no fear in love; but perfect love casteth out fear.",
                "There will always be some delightful mysteries in your life.",
                "There will be big changes for you but you will be happy.",
                "There's at least one fool in every married couple.",
                "There's so much to say but your eyes keep interrupting me.",
                "Think twice before speaking. But don't say 'think think click click'.",
                "This file will self-destruct in five minutes.",
                "Those of you who think you know everything are annoying  those of us who do.",
                "Those who are prospering do not argue about taxes.",
                "To criticize the incompetent is easy; it is more difficult to criticize the competent.",
                "To be trusted is a greater compliment than to be loved.",
                "To do is to be - Nietzsche To be is to do - Sartre Do be do be do - Sinatra",
                "To give happiness is to deserve happiness.",
                "To iterate is human, to recurse is divine.",
                "To keep your friends treat them kindly; to kill them, treat them often.",
                "To laugh at men of sense is the privilege of fools.",
                "To profit from good advice requires more wisdom than to give it.",
                "To refuse praise is to seek praise twice.",
                "To save a single life is better than to build a seven story pagoda.",
                "Traveler, there is no path, paths are made by walking.",
                "True happiness will be found only in true love.",
                "Trust him, but still keep your eyes open.",
                "Try to divide your time evenly to keep others happy.",
                "Try to value useful qualities in one who loves you.",
                "Valuable insights and your persuasive ability achieve results.",
                "We do not recommend the use of 'roman numerals' in western electric information.",
                "We prefer to speak evil of ourselves than not speak of ourselves at all.",
                "We promise according to our hopes, and perform according to our fears.",
                "We read to say that we have read.",
                "What makes us so bitter against people who outwit us is that they",
                "think themselves cleverer than we are.",
                "What no spouse of a writer can ever understand is that a writer is working when he's staring out the window.",
                "What orators lack in depth they make up in length.",
                "What passes for woman's intuition is often nothing more than man's transparency.",
                "What this country needs is a dime that will buy a good five-cent bagel.",
                "When God endowed human beings with brains, He did not intend to guarantee them.",
                "When the wind is great, bow before it; when the wind is heavy, yield to it.",
                "When you become used to never being alone, you may consider yourself Americanized.",
                "When you go out to buy, don't show your silver.",
                "Whenever I feel like exercise, I lie down until the feeling passes.",
                "Why did the Lord give us so much quickness of movement unless it was to avoid responsibility?",
                "Wisdom and good sense guard life from harm.",
                "With clothes the new are best, with friends the old are best.",
                "With a mind like yours, who needs a body.",
                "Without fools there would be no wisdom.",
                "Without health you cannot enjoy wealth or happiness.",
                "Words are the voice of the heart.",
                "Words must be weighed, not counted.",
                "Worth seeing?  Yes, but not worth going to see.",
                "You are a bundle of energy always on the go.",
                "You are a general favorite among your many friends.",
                "You are a person of firm, yet honest intentions.",
                "You are always busy.",
                "You are an individual interested in foreward thrust and the future.",
                "You are broad minded and socially active.",
                "You are capable of planning your future.",
                "You are careful and systematic in your business arrangements.",
                "You are clever, alert, and intellectual.",
                "You are deeply attached to your friends and acquaintances.",
                "You are dishonest, but never to the point of hurting a friend.",
                "You are fair-minded, just and loving.",
                "You are faithful to duty, adaptable to environment, loyal to friends.",
                "You are farsighted, a good planner, an ardent lover, and a faithful friend.",
                "You are fixed in your opinions and will not be easily moved from your purpose.",
                "You are generous and always think of the other fellow.",
                "You are going to have a new  -  loveaffair.",
                "You are heading for a land of sunshine.",
                "You are interested in higher education whether material or spiritual",
                "You are magnetic in your bearing.",
                "You are next in line for promotion in your firm.",
                "You are never selfish with your advice or your help.",
                "You are scrupulously honest, frank, and straightforward.",
                "You are secretive in your dealings but never to the extent of trickery.",
                "You are standing on my toes.",
                "You are the center of every group's attention.",
                "Your are the guiding star of his existence.",
                "You are tricky, but never to the point of dishonesty.",
                "You are versatile, energetic, artistic and good-natured.",
                "You are witty and fond of fun.",
                "You can do very well in speculation where land or anything to do with earth is concerned.",
                "You cannot kill time without injuring eternity.",
                "You cannot propel yourself forward by patting yourself on the back.",
                "You display the wonderful traits of charm and courtesy.",
                "You enjoy the company of other people.",
                "You have a deep appreciation of the arts and music.",
                "You have a deep interest in all that is artistic.",
                "You have a reputation for being thoroughly reliable and trustworthy.",
                "You have a strong appeal for members of the opposite sex.",
                "You have a strong desire for a home and your family interests come first.",
                "You have a truly strong individuality",
                "You have a will that can be  influenced by all with whom you come in contact.",
                "You have a yearning for perfection.",
                "You have an ability to sense and know higher truth.",
                "You have an ambitious nature and may make a name for yourself.",
                "You have an unusual equipment for success.  Be sure to use it properly.",
                "You have an unusual magnetic personality.",
                "You have an unusual understanding of the problems of human relationship.",
                "You have been selected for a secret mission.",
                "You have had a long-term stimulation relative to business.",
                "You have literary talent that you should take pains to develop.",
                "You have many friends and very few enemies.",
                "You have no real enemies.",
                "You have the attitude of a winner.",
                "You have the power to influence all with whom you come in contact.",
                "You like participating in competitive sports.",
                "You like to form new friendships and make new acquaintances.",
                "You love peace.",
                "You love your home and want it to be beautiful.",
                "You may attend a party where strange customs prevail.",
                "You may be conservative, cautious and practical.",
                "You must be patient for a little while.",
                "You need not worry about your future.",
                "You never hesitate to tackle the most difficult problems.",
                "You plan things that you do not even attempt because of your extreme caution",
                "You prefer the company of the opposite sex, but are well liked by your own.",
                "You recoil from the crude; you tend naturally toward the exquisite.",
                "You seek to shield those you love and you like the role of the provider",
                "You shall be rewarded for a dastardly deed.",
                "You understand human nature and sympathize with its weakness.",
                "You will always be successful in your business or professional career.",
                "You will always get what you want through your charm and personality.",
                "You will always have good luck in your personal affairs.",
                "You will attract cultured and artistic people to your home.",
                "You will be a great success both in the business world and society.",
                "You will be a guest at a gay party that'll have important consequences for you.",
                "You will be aided greatly by a person whom you thought to be unimportant",
                "You will be awarded a medal for disregarding safety in saving someone.",
                "You will be awarded some great honor.",
                "You will be called upon to help a friend in trouble.",
                "You will be given a post of trust and responsibility.",
                "You will be honored for contributing your time and skill to a worthy cause",
                "You will be made happy by receipt of good news.",
                "You will be married within a year.",
                "You will be proud in manner but tolerant and generous.",
                "You will be recognized and honored as a community leader.",
                "You will be singled out for promotion in your work.",
                "You will be successful in love.",
                "You will be successful in your work.",
                "You will be surprised by a loud noise.",
                "You will be surrounded by luxury.",
                "You will be traveling and coming into a fortune.",
                "You will be unusually successful in business.",
                "You will engage in a profitable business activity.",
                "You will engage in a profitable friendship.",
                "You will enjoy the high praise of solving a problem of long standing.",
                "You will gain money by a speculation or lottery.",
                "You will have good luck and overcome many hardships.",
                "You will have long and healthy life.",
                "You will have many friends when you use corkscrew.",
                "You will hear good news from one you thought unfriendly to you.",
                "You will inherit some money or a small piece of land.",
                "You will marry your present lover and be happy.",
                "You will meet an important person who will help you advance professionally.",
                "You will never know hunger.",
                "You will overcome the attacks of jealous associates.",
                "You will probably marry after a very brief courtship.",
                "You will receive a legacy which will place you above want.",
                "You will secure the greatest degree of happiness if you marry young.",
                "You will soon meet a person who will play an important role in your life.",
                "You will soon take that long awaited vacation.",
                "You will step on the soil of many countries.",
                "You will triumph over your enemy.",
                "You will visit some faraway land that has long been in your waking thoughts.",
                "You will win success in whatever calling you adopt.",
                "Your aims are high, and you are capable of much.",
                "Your business will assume vast proportions.",
                "Your depth of comprehension may tend to make you lax in worldly ways.",
                "Your domestic life may be harmonious",
                "Your first impressions of people are best.",
                "Your happiness is intertwined with your outlook on life.",
                "Your heart is pure, and your mind clear, and your soul devout.",
                "Your help will be needed in an embarrassing situation.",
                "Your long forgotten kindness to someone will bring a substantial sum of money.",
                "Your love life will be happy and harmonious.",
                "Your lover will never wish to leave you",
                "Your mind understands what you have been taught; your heart, what is true",
                "Your mode of life will be changed for the better because of good news soon.",
                "Your mode of life will be changed for the better because of new developments.",
                "Your nature demands love and your happiness depends on it.",
                "Your next acquaintance will be the right one.",
                "Your own qualities will help prevent your advancement in the world.",
                "Your place in the path of life is in the driver's seat.",
                "Your present plans will be successful",
                "Your reasoning powers are good, and you are a fairly good planner.",
                "Your society will be sought by people of taste and refinement.",
                "Your talents will be recognized and suitably rewarded.",
                "Your temporary financial embarrassment will be relieved in a surprising manner.",
                "Youth had been a habit of hers so long that she could not part with it.",
                "eHpl ! Imat arppdei sndi eht eDP-P11"
            };
            bot.SendReply(e, this.PickRandom(replies, e.Sender));
        }

        public string PickRandom(string[] selection, string sender)
        {
            Random random = new Random();
            return selection[random.Next(selection.Length)].Replace("(sender)", sender);
        }
    }
}
